// SPDX-License-Identifier: MIT
// AUTOGENERATED - DON'T MANUALLY CHANGE
pragma solidity >=0.6.0;

import {IPoolAddressesProvider, IPool, IPoolConfigurator, IAaveOracle, IPoolDataProvider, IACLManager, ICollector} from './AaveV3.sol';

library AaveV3Goerli {
  IPoolAddressesProvider internal constant POOL_ADDRESSES_PROVIDER =
    IPoolAddressesProvider(0x4A4e3D9eE2CAD18D62bb8f6252C4A460279fC1f7);

  IPool internal constant POOL = IPool(0xdcd1Ff8AA5cF289d17304dA2cdbdA3225130e365);

  IPoolConfigurator internal constant POOL_CONFIGURATOR =
    IPoolConfigurator(0xEC019De4C9b04B882f2503b5A72e7d2cecAF8Ef9);

  IAaveOracle internal constant ORACLE = IAaveOracle(0xc48f71233975564d15b985986b92f1494a999E85);

  IPoolDataProvider internal constant AAVE_PROTOCOL_DATA_PROVIDER =
    IPoolDataProvider(0xB64FB0e0Be8D5BfbC4348Fd747eEf7D96322E42b);

  IACLManager internal constant ACL_MANAGER =
    IACLManager(0x730D4c706c6c77730702C8939e44a2c6a0820180);

  address internal constant ACL_ADMIN = 0xc6C1eF70746F6Bed0A43C912B2B2047f25d3eA87;

  address internal constant COLLECTOR = 0xcb8f88F5B1453a9bB72af091c2e305eaf2FE030b;

  ICollector internal constant COLLECTOR_CONTROLLER =
    ICollector(0x1821610a350D43c3dA271755B39B970783b8b384);

  address internal constant DEFAULT_INCENTIVES_CONTROLLER =
    0x0000000000000000000000000000000000000000;

  address internal constant DEFAULT_A_TOKEN_IMPL_REV_1 = 0x97BF4EB6c8b62c6C3567C458Bdf5c7b2b270fDEa;

  address internal constant DEFAULT_VARIABLE_DEBT_TOKEN_IMPL_REV_1 =
    0xE5013dF7b1035c6b3aFF46F972e941DBeAF79FC7;

  address internal constant DEFAULT_STABLE_DEBT_TOKEN_IMPL_REV_1 =
    0x7ba9bC30aa5AB894700b6A32e37cfd4EC28e01c6;

  address internal constant EMISSION_MANAGER = 0x0000000000000000000000000000000000000000;

  address internal constant WETH_GATEWAY = 0x35846aFf520988f0E856F76fEC5656357a8c46E7;

  address internal constant FAUCET = 0x13550d05Ea6a8907d295e4f17e707E4b43d2e26D;

  address internal constant WALLET_BALANCE_PROVIDER = 0x04Cc5547fD6b8ef7923AEd1c0fBf0E51D3f3F97e;

  address internal constant UI_POOL_DATA_PROVIDER = 0xFc1A5E22A49098BD721Ba4d8E4D6540C84CAb14b;

  address internal constant GAUGE_FACTORY = 0xF6bEe4C1B0aBBC88Df5BF46062C26BE2007e36D7;

  address internal constant GAUGE_CONTROLLER = 0x4c2D5F39D7e936Ca9BE04feB665971e61B793Acb;

  address internal constant MINTER = 0xf38F371b16Aa1e3396A64BC03e4995C9B67fb3F3;
}

library AaveV3GoerliAssets {
  address internal constant WETH_UNDERLYING = 0x6Cc53D3AeaEe7aAfbd2Ac304AA64d017E6cb4f2a;

  address internal constant WETH_A_TOKEN = 0x5828C686Ca8670bF4ebEaDa1eFd3E6667dB95313;

  address internal constant WETH_V_TOKEN = 0xd89b6104265f07Bf32899938D64EE1Cd14698FAB;

  address internal constant WETH_S_TOKEN = 0x0F82A7C5349D1122f3fC7b9AAf838094f5406263;

  address internal constant WETH_ORACLE = 0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e;

  address internal constant WETH_INTEREST_RATE_STRATEGY =
    0x243F49c98f2d0279fefF60888E7CceE6acF949ab;

  address internal constant wstETH_UNDERLYING = 0x050af32f9FEA93231fCFf7a44181A2a7dA9b4A80;

  address internal constant wstETH_A_TOKEN = 0x1a0D397E269a6d3A78bc45DafF5332172906cDfE;

  address internal constant wstETH_V_TOKEN = 0x6801980fE99f275663006d13b33E1462D369271f;

  address internal constant wstETH_S_TOKEN = 0x5a3eC67f7056c4F4026682f575F6af1D1cC2Ee27;

  address internal constant wstETH_ORACLE = 0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e;

  address internal constant wstETH_INTEREST_RATE_STRATEGY =
    0x7a9029219480496dD6488052A1659DFCCA37E2B3;

  address internal constant USDT_UNDERLYING = 0x1C6Cf7Df9dFC87d2C373FF12F713e3222356783f;

  address internal constant USDT_A_TOKEN = 0xaFb8EECcbb65D95afAF8E14D918387D3702D2D28;

  address internal constant USDT_V_TOKEN = 0x77151cd24BCD90b07e50Dbb17FF021f6119F24aa;

  address internal constant USDT_S_TOKEN = 0xc5Ce89886Eb9D483D0dA8156792c397bee767CAc;

  address internal constant USDT_ORACLE = 0x0d79df66BE487753B02D015Fb622DED7f0E9798d;

  address internal constant USDT_INTEREST_RATE_STRATEGY =
    0x4E5e1a85Df8EE82cda738E64F1585aB9c9548De0;

  address internal constant USDC_UNDERLYING = 0x832c2B8efb16Ffabc73e1F23D31f3B574Ff0b7F6;

  address internal constant USDC_A_TOKEN = 0xB47cd8493838Fd2a4d044199d189518988422fFB;

  address internal constant USDC_V_TOKEN = 0x9A422f6a0514d2199549bdaae721df756D8FBf09;

  address internal constant USDC_S_TOKEN = 0x05A63468991CF5eDb88C03f3ea1857d9dC70F2e5;

  address internal constant USDC_ORACLE = 0xAb5c49580294Aff77670F839ea425f5b78ab3Ae7;

  address internal constant USDC_INTEREST_RATE_STRATEGY =
    0x28Baf782eF42574a09815F6de81913d8871706a3;

  address internal constant HOPE_UNDERLYING = 0xdC857E0d4C850deAe3a7735390243d3c444E552F;

  address internal constant HOPE_A_TOKEN = 0x2173892d2F128Ed2Cb77e266351baA30ED404caa;

  address internal constant HOPE_V_TOKEN = 0xa79512F8113bF1a14C6BB5f5f6e9a51cd0F9EEb8;

  address internal constant HOPE_S_TOKEN = 0x8f29C7cE88cC18A29C13A8E6d42FeE8CaCE9718b;

  address internal constant HOPE_ORACLE = 0x18a22B5667Ca2B304979465bde9ca9F14E7c312B;

  address internal constant HOPE_INTEREST_RATE_STRATEGY =
    0x1fcCCD70c0E95ef5fE5bcD6DE310623b80495A69;

  address internal constant stHOPE_UNDERLYING = 0x09B4621e2A9dBd37550dC4923E60Ff0782Ef9250;

  address internal constant stHOPE_A_TOKEN = 0x61C0407e54f1A3658a721B4AFe5214a60DBe193B;

  address internal constant stHOPE_V_TOKEN = 0x3d9a2479Fa542f534Cd3963028C83B8AA81420cd;

  address internal constant stHOPE_S_TOKEN = 0xafD2b1b1E5D3F366F29FaC95350eA46B560B5739;

  address internal constant stHOPE_ORACLE = 0x18a22B5667Ca2B304979465bde9ca9F14E7c312B;

  address internal constant stHOPE_INTEREST_RATE_STRATEGY =
    0x1fcCCD70c0E95ef5fE5bcD6DE310623b80495A69;

  address internal constant WBTC_UNDERLYING = 0x5e457e88503c47C85C106edB4e27208bBBA26d7f;

  address internal constant WBTC_A_TOKEN = 0xAbC6277aE6153a30dE06907ade770bD92a807bae;

  address internal constant WBTC_V_TOKEN = 0x295818eA25828513D21672289f21072e943FBBD1;

  address internal constant WBTC_S_TOKEN = 0x771514aD2F813d0c083B1C25CE26ac1A97652cAa;

  address internal constant WBTC_ORACLE = 0xA39434A63A52E749F02807ae27335515BA4b07F7;

  address internal constant WBTC_INTEREST_RATE_STRATEGY =
    0x4b6eC5f518ee0A9e54ce81F0F7Ede9bD679BcBbb;
}
