// SPDX-License-Identifier: MIT
// AUTOGENERATED - DON'T MANUALLY CHANGE
pragma solidity >=0.6.0;

import {IPoolAddressesProvider, IPool, IPoolConfigurator, IAaveOracle, IPoolDataProvider, IACLManager, ICollector} from './AaveV3.sol';

library AaveV3Goerli {
  IPoolAddressesProvider internal constant POOL_ADDRESSES_PROVIDER =
    IPoolAddressesProvider(0x07500ACB739503c45ffa49B1a0211938C3eE5cfE);

  IPool internal constant POOL = IPool(0x90EF4D41958459234db5f80DB56cddAe35fc7F88);

  IPoolConfigurator internal constant POOL_CONFIGURATOR =
    IPoolConfigurator(0x47c7FB2b5D490df74f09889D2DdAd181925713Fc);

  IAaveOracle internal constant ORACLE = IAaveOracle(0x5C0f15815A36e97493668374D61e9Cf6e4A9E054);

  IPoolDataProvider internal constant AAVE_PROTOCOL_DATA_PROVIDER =
    IPoolDataProvider(0xF41e680d6fA2C06585C6144B04F44182D4D67aF4);

  IACLManager internal constant ACL_MANAGER =
    IACLManager(0x132368966719155A8AB0D29D887f80700460f350);

  address internal constant ACL_ADMIN = 0xc6C1eF70746F6Bed0A43C912B2B2047f25d3eA87;

  address internal constant COLLECTOR = 0xF6Ae5D58173bDcd5eDD75926825322B31F665A20;

  ICollector internal constant COLLECTOR_CONTROLLER =
    ICollector(0xaedbA9EA033bCe3209983F3CBa89f6eEBcADfff4);

  address internal constant DEFAULT_INCENTIVES_CONTROLLER =
    0x0000000000000000000000000000000000000000;

  address internal constant DEFAULT_A_TOKEN_IMPL_REV_1 = 0xd5fc0Ad9AE9A8dF3Ea81Da96C28b03022C518CD4;

  address internal constant DEFAULT_VARIABLE_DEBT_TOKEN_IMPL_REV_1 =
    0x18a592a49fF2eabA78ad23e0E3F4bB0DdBfd2B92;

  address internal constant DEFAULT_STABLE_DEBT_TOKEN_IMPL_REV_1 =
    0xe70E99b6A19B776DE2F0d45670EC34F7E897E285;

  address internal constant EMISSION_MANAGER = 0x0000000000000000000000000000000000000000;

  address internal constant WETH_GATEWAY = 0xa1c4C23419bF0E6a64e26971f736Dc89B749867A;

  address internal constant FAUCET = 0x13550d05Ea6a8907d295e4f17e707E4b43d2e26D;

  address internal constant WALLET_BALANCE_PROVIDER = 0xA33f3600d7a39D4CAA3CA6fe20044584e7da14D6;

  address internal constant UI_POOL_DATA_PROVIDER = 0x190aE06f2dF16BDcddFaEeB6949A6ef94a12a6a0;

  address internal constant GAUGE_FACTORY = 0x628b88aaa37202a3c4e977F867bfc6D5d9CB45e1;

  address internal constant GAUGE_CONTROLLER = 0x4c2D5F39D7e936Ca9BE04feB665971e61B793Acb;

  address internal constant MINTER = 0xf38F371b16Aa1e3396A64BC03e4995C9B67fb3F3;
}

library AaveV3GoerliAssets {
  address internal constant WETH_UNDERLYING = 0x6Cc53D3AeaEe7aAfbd2Ac304AA64d017E6cb4f2a;

  address internal constant WETH_A_TOKEN = 0x4e90ec5308f689C1f738E78eA9aa43A7b3800633;

  address internal constant WETH_V_TOKEN = 0x30f760b9F1bdc6f01F8673d378641797A725941A;

  address internal constant WETH_S_TOKEN = 0xcC66C5976b5D3F9F1cC1896f85Ab66B3fbb87C31;

  address internal constant WETH_ORACLE = 0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e;

  address internal constant WETH_INTEREST_RATE_STRATEGY =
    0x089938B6eA609181c9089DD421652160A0aCc5E1;

  address internal constant wstETH_UNDERLYING = 0x050af32f9FEA93231fCFf7a44181A2a7dA9b4A80;

  address internal constant wstETH_A_TOKEN = 0x3b1b59E10A7D2884d0Ee4651D215E2445401dB21;

  address internal constant wstETH_V_TOKEN = 0xfc0DF3F11803ef92cd995E9686bb529AEBd4f8a7;

  address internal constant wstETH_S_TOKEN = 0xde07e0D41fe203080De52132C56ea3A52c7830a0;

  address internal constant wstETH_ORACLE = 0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e;

  address internal constant wstETH_INTEREST_RATE_STRATEGY =
    0xc9FDF1947881d358a13eD494915713C1d8B39575;

  address internal constant USDT_UNDERLYING = 0x1C6Cf7Df9dFC87d2C373FF12F713e3222356783f;

  address internal constant USDT_A_TOKEN = 0x613fB31BEd683445A4B813F9207C2502F61fADd6;

  address internal constant USDT_V_TOKEN = 0x1DAB590D1631Baa62ce9D371efB8573EeE76D8d9;

  address internal constant USDT_S_TOKEN = 0x9697A0e9ef23dD6514ee0aA8D8186A0C16828646;

  address internal constant USDT_ORACLE = 0x0d79df66BE487753B02D015Fb622DED7f0E9798d;

  address internal constant USDT_INTEREST_RATE_STRATEGY =
    0xF4476067A7FdBc178D96BD951E616335E40Fe20e;

  address internal constant USDC_UNDERLYING = 0x832c2B8efb16Ffabc73e1F23D31f3B574Ff0b7F6;

  address internal constant USDC_A_TOKEN = 0xc4b8403ABfae6e3B3b135110ee6B217126792481;

  address internal constant USDC_V_TOKEN = 0x4c81717159b4af134f9EFfdad96D206C8C88aBA9;

  address internal constant USDC_S_TOKEN = 0x90cECE338478Ec2917E2788aa6b76D5aB3804865;

  address internal constant USDC_ORACLE = 0xAb5c49580294Aff77670F839ea425f5b78ab3Ae7;

  address internal constant USDC_INTEREST_RATE_STRATEGY =
    0x892740A40ae94dDFe52Ce1aB526A45CD3f1a04a2;

  address internal constant HOPE_UNDERLYING = 0xdC857E0d4C850deAe3a7735390243d3c444E552F;

  address internal constant HOPE_A_TOKEN = 0x4A637Da57611B3a598e50f8A393489c4aD007566;

  address internal constant HOPE_V_TOKEN = 0xeaacA212862f84746cc106EEe21305BB012b8373;

  address internal constant HOPE_S_TOKEN = 0xC208B5689306a685BAD14Ea9f3D8AB5e40eF381f;

  address internal constant HOPE_ORACLE = 0x211f184c1EA0Cf4bB23BFD7a5a432628D90cEa97;

  address internal constant HOPE_INTEREST_RATE_STRATEGY =
    0x9802b05Fef8D4BD8835E9dF950fCD9A08ad20777;

  address internal constant stHOPE_UNDERLYING = 0x09B4621e2A9dBd37550dC4923E60Ff0782Ef9250;

  address internal constant stHOPE_A_TOKEN = 0x0264ff940300aeCCfc95645C54e7B00C35192c2f;

  address internal constant stHOPE_V_TOKEN = 0x5ffE515B8E8bbF6eFd6897184b5fe11710e6A3E4;

  address internal constant stHOPE_S_TOKEN = 0x2511B86A097d303eb31D084Df39E299F13736f9D;

  address internal constant stHOPE_ORACLE = 0x211f184c1EA0Cf4bB23BFD7a5a432628D90cEa97;

  address internal constant stHOPE_INTEREST_RATE_STRATEGY =
    0x9802b05Fef8D4BD8835E9dF950fCD9A08ad20777;

  address internal constant WBTC_UNDERLYING = 0x5e457e88503c47C85C106edB4e27208bBBA26d7f;

  address internal constant WBTC_A_TOKEN = 0x61bf80862094a4afe4889B6D3f6cd8B936d97F6A;

  address internal constant WBTC_V_TOKEN = 0x3996438bA321ADC6a9dF4D6704B1d2c946EA6230;

  address internal constant WBTC_S_TOKEN = 0x338e82f5BdCB027CDC20d63A1561cdAe1f505daE;

  address internal constant WBTC_ORACLE = 0xA39434A63A52E749F02807ae27335515BA4b07F7;

  address internal constant WBTC_INTEREST_RATE_STRATEGY =
    0xEdb9757b40f26290CC7FB90Fd2F32e2e73fC3A67;
}
