// SPDX-License-Identifier: MIT
// AUTOGENERATED - DON'T MANUALLY CHANGE
pragma solidity >=0.6.0;

import {IPoolAddressesProvider, IPool, IPoolConfigurator, IAaveOracle, IPoolDataProvider, IACLManager, ICollector} from './AaveV3.sol';

library AaveV3Sepolia {
  IPoolAddressesProvider internal constant POOL_ADDRESSES_PROVIDER =
    IPoolAddressesProvider(0xc4099668b3417EAfB44ee9F8c68562966dF59520);

  IPool internal constant POOL = IPool(0x7d1FBdB05fCEFCE8feFcffA028aD104027482a19);

  IPoolConfigurator internal constant POOL_CONFIGURATOR =
    IPoolConfigurator(0x9b9270e84Cc3061558B6A3A0402cBD63c63D2FC8);

  IAaveOracle internal constant ORACLE = IAaveOracle(0x3BCcEB9e6633A601A6B94A83b2c279387EE04134);

  IPoolDataProvider internal constant AAVE_PROTOCOL_DATA_PROVIDER =
    IPoolDataProvider(0x47692E660Cd8735743D54012538E9c2c37071c32);

  IACLManager internal constant ACL_MANAGER =
    IACLManager(0x10649dCc6C1e889965A862E14f40d02F8baFaDCC);

  address internal constant ACL_ADMIN = 0x3141f8D6BE4e4d9137577798C1e127Db81D196d7;

  address internal constant COLLECTOR = 0xf385DEb587164ddc8DF2D282A64ec12Afb1acFdd;

  ICollector internal constant COLLECTOR_CONTROLLER =
    ICollector(0x5b3743cBA8250EE8dC953519111A98B4Fd6a46AB);

  address internal constant DEFAULT_INCENTIVES_CONTROLLER =
    0xd0A1e9439ce25A644A98f0f4d69bED4f1cFa78d9;

  address internal constant DEFAULT_A_TOKEN_IMPL_REV_1 = 0x9360720E194BD8eD61745323d501ec87AC7bf5AF;

  address internal constant DEFAULT_VARIABLE_DEBT_TOKEN_IMPL_REV_1 =
    0xE26B621C5ec24BD85FB26dB63f618E989d8563A7;

  address internal constant DEFAULT_STABLE_DEBT_TOKEN_IMPL_REV_1 =
    0xED93FBA28f6Feb72fC84c5d5271eECEaC507C98f;

  address internal constant EMISSION_MANAGER = 0x84DdF836249CbE3f21F9A55BCaa13A8366852B46;

  address internal constant WETH_GATEWAY = 0xbBc8437c2b170831dBc7BED848f7a1b2A0F3dB9c;

  address internal constant FAUCET = 0xA249fFA2e10B925C8c84Df0e073C76F24B7D88b0;

  address internal constant WALLET_BALANCE_PROVIDER = 0x5028a26Ba880F72eD44b6E4cf024f318217869b6;

  address internal constant UI_POOL_DATA_PROVIDER = 0x832c2B8efb16Ffabc73e1F23D31f3B574Ff0b7F6;

  address internal constant UI_INCENTIVE_DATA_PROVIDER = 0x31f9f58F85679282FF0dD5d4090020b3cC5bbFc4;
}

library AaveV3SepoliaAssets {
  address internal constant DAI_UNDERLYING = 0xe66Ea714Db8FdBba759eD55FB586F3a25b018477;

  address internal constant DAI_A_TOKEN = 0xbcCef996b5C90a7Efbe92F8E5B9F426e0614aeB7;

  address internal constant DAI_V_TOKEN = 0xa2C6beAbEE1EE8062eC13b462c49B67eD82956b9;

  address internal constant DAI_S_TOKEN = 0x81370F165A2eE33aB273a8D7cA7b0f4d19bcC7f8;

  address internal constant DAI_ORACLE = 0x4581B432FC3a2c385bD20A1aD4abF5819EbB083c;

  address internal constant DAI_INTEREST_RATE_STRATEGY = 0x521E8dB0997e83102ae50e42ECa515381B0bd531;

  address internal constant LINK_UNDERLYING = 0x6eDECF42E7F9e5099ff0FB4c1C2138065eA4FCaa;

  address internal constant LINK_A_TOKEN = 0xc716727303c7F4Cc98e9659Fb1547849bFB0B37E;

  address internal constant LINK_V_TOKEN = 0xeC2f55DCc22aD67a93CfD43D164ae17392815d0E;

  address internal constant LINK_S_TOKEN = 0x63F76899253F6d994F1D6D171c4c55cbAC46cEeB;

  address internal constant LINK_ORACLE = 0xC172eF994Be0f67921D6A5dD2fD5Bc5f30cbE243;

  address internal constant LINK_INTEREST_RATE_STRATEGY =
    0x7636109F1E8aC4568634D8339FbD42a2d064f1f3;

  address internal constant USDC_UNDERLYING = 0xc9f414576c45EDe2AA9582765220630ffD993156;

  address internal constant USDC_A_TOKEN = 0x2bb8934BcE71fD89ADAFf2811d5A71B569CEb9Df;

  address internal constant USDC_V_TOKEN = 0x09beC87eA5843c8e871F17c6a8E7cDd1e2cF3741;

  address internal constant USDC_S_TOKEN = 0xceA4B195D3cca0646e671A59051408Bcb7F68139;

  address internal constant USDC_ORACLE = 0xf79c75Eb040Ed7A52b8F8bAaf84fe3A0c906a9d9;

  address internal constant USDC_INTEREST_RATE_STRATEGY =
    0x4947B606EBd23bC35993950a645113Bb17321074;

  address internal constant WBTC_UNDERLYING = 0xf381160F22601dbD1F50F6bFf9c5053Ed1746Ca8;

  address internal constant WBTC_A_TOKEN = 0xddd2aB1a73D1B2022052989684dea4B678461b89;

  address internal constant WBTC_V_TOKEN = 0xa4EFb55D862266508A48efB2DA5628F5bf873b99;

  address internal constant WBTC_S_TOKEN = 0xF5E3F2C02b07Ae7aE7c31f4B0c7B3870D8a38070;

  address internal constant WBTC_ORACLE = 0xb7d841097C895bF80E52d8029e6Eae69e1c795BE;

  address internal constant WBTC_INTEREST_RATE_STRATEGY =
    0x7636109F1E8aC4568634D8339FbD42a2d064f1f3;

  address internal constant WETH_UNDERLYING = 0xb2DB1476F25381D1e73a2A5A3a71c0374DD87A33;

  address internal constant WETH_A_TOKEN = 0x9E68CBf14f8d0afAeC31f84f547d073aA3b52156;

  address internal constant WETH_V_TOKEN = 0xD36bfD56c972fA1C0E0c0F410EaF0D9C2EcF4a42;

  address internal constant WETH_S_TOKEN = 0x451e8658C2a9BbA95a531660AdC14A3625a47511;

  address internal constant WETH_ORACLE = 0xBE1739Cc5Ed90D2F2c33199C552b4f26b8EA12c5;

  address internal constant WETH_INTEREST_RATE_STRATEGY =
    0x7636109F1E8aC4568634D8339FbD42a2d064f1f3;

  address internal constant USDT_UNDERLYING = 0x9da61a54736c36D4B290faeB40A744F45081Ce4E;

  address internal constant USDT_A_TOKEN = 0x8B1716a88ad00F06F90dB720BF8379166d8c78Ef;

  address internal constant USDT_V_TOKEN = 0x1c63aD213B612F7F21FE3E6F7Bc1e94C7E1582A9;

  address internal constant USDT_S_TOKEN = 0xf100f83dc778FBFF484fcE38331b6a40dcf90212;

  address internal constant USDT_ORACLE = 0xF83c887AA48ceD069FB32b3b84f4Ee10e43DA518;

  address internal constant USDT_INTEREST_RATE_STRATEGY =
    0x4947B606EBd23bC35993950a645113Bb17321074;

  address internal constant HOPE_UNDERLYING = 0xed4d1edE4aBC75FD83D725F327045952BB92DEFf;

  address internal constant HOPE_A_TOKEN = 0x623d1c8B887362762A28b9145F4A6dceAe4995fB;

  address internal constant HOPE_V_TOKEN = 0x81b4648059e285A47A179f720cB396F58f1971c3;

  address internal constant HOPE_S_TOKEN = 0x4B5112Ca07d097F52d56A89889b03F38ad79032e;

  address internal constant HOPE_ORACLE = 0x4051f5190541E59275d4011501E727afa5d7e32B;

  address internal constant HOPE_INTEREST_RATE_STRATEGY =
    0x7636109F1E8aC4568634D8339FbD42a2d064f1f3;

  address internal constant EURS_UNDERLYING = 0xF8268B0aae68A11aC0F5c7f8D5e251865A99DF29;

  address internal constant EURS_A_TOKEN = 0x645880965Eec147bC5B916Ae1E1F3431eacddC43;

  address internal constant EURS_V_TOKEN = 0xB23BcC9D4C69007e8ab296F894B954A29502FDE4;

  address internal constant EURS_S_TOKEN = 0x65c9D5dF6De1014542fE93e15A4Ca7537F69d522;

  address internal constant EURS_ORACLE = 0xcb346CAFE5fd58C0Ecd91fc056f1132c6DEce6De;

  address internal constant EURS_INTEREST_RATE_STRATEGY =
    0x4947B606EBd23bC35993950a645113Bb17321074;
}
