// SPDX-License-Identifier: MIT
// AUTOGENERATED - DON'T MANUALLY CHANGE
pragma solidity >=0.6.0;

import {IPoolAddressesProvider, IPool, IPoolConfigurator, IAaveOracle, IPoolDataProvider, IACLManager, ICollector} from './AaveV3.sol';

library AaveV3Goerli {
  IPoolAddressesProvider internal constant POOL_ADDRESSES_PROVIDER =
    IPoolAddressesProvider(0xa9d27b54F56CcF3E651465Dc1cda82896fC0FfF7);

  IPool internal constant POOL = IPool(0x19B9cE0c09A00BDD9190240f2055def7760C4d1E);

  IPoolConfigurator internal constant POOL_CONFIGURATOR =
    IPoolConfigurator(0x848BA7525CC84399d7cDdddeDAA4e3a8cEC277ba);

  IAaveOracle internal constant ORACLE = IAaveOracle(0x1acca61b27E97aAcf8330c78A062F4123A79f243);

  IPoolDataProvider internal constant AAVE_PROTOCOL_DATA_PROVIDER =
    IPoolDataProvider(0xd81c290B780e60EF25B81063D3Dc2a2706de3E27);

  IACLManager internal constant ACL_MANAGER =
    IACLManager(0xDa57F7C5eB046ac7256Cd814ddF2722131c3Ff19);

  address internal constant ACL_ADMIN = 0xc6C1eF70746F6Bed0A43C912B2B2047f25d3eA87;

  address internal constant COLLECTOR = 0xC2E7266ED9397Bf0b4AC50AF8C65066FbfF0F8e9;

  ICollector internal constant COLLECTOR_CONTROLLER =
    ICollector(0x13712AcB9231c6cba5828Aa978748f016f7A350E);

  address internal constant DEFAULT_INCENTIVES_CONTROLLER =
    0x0000000000000000000000000000000000000000;

  address internal constant DEFAULT_A_TOKEN_IMPL_REV_1 = 0x7877338B1Bd920544069C94C08922907460E1A04;

  address internal constant DEFAULT_VARIABLE_DEBT_TOKEN_IMPL_REV_1 =
    0x6fe715bBed091d1130B999A4871353B91f49fF7C;

  address internal constant DEFAULT_STABLE_DEBT_TOKEN_IMPL_REV_1 =
    0x485dA1cD692a986EC289B974Af739685d9bF6B56;

  address internal constant EMISSION_MANAGER = 0x0000000000000000000000000000000000000000;

  address internal constant WETH_GATEWAY = 0x5aC0d35C55E56F70F9a2F7b9caC5757BaadE96de;

  address internal constant FAUCET = 0x89190c0CB7AD5591c349d080DF40663dA9c3d83b;

  address internal constant WALLET_BALANCE_PROVIDER = 0x75e59165d7145B3E4B357Aa7Ad272aaf03b82505;

  address internal constant UI_POOL_DATA_PROVIDER = 0xF80e3E61b87855AA2DEd9Ba6B6CCe3CAd1f76551;

  address internal constant GAUGE_FACTORY = 0xdeB2e5895653574ef759Ddae11212564553eC2B7;

  address internal constant GAUGE_CONTROLLER = 0xb4fE4653F175C36e8EEab35229fdB5702789B9F2;

  address internal constant MINTER = 0x3c2AB5E5D31872B920497bD787cFFAba9fB3615A;
}

library AaveV3GoerliAssets {
  address internal constant DAI_UNDERLYING = 0x5B71dC777A8aDCba065A644e30BBEeB8fCca273f;

  address internal constant DAI_A_TOKEN = 0xBc9cc41995E3E314ff6De75B30202a281257142D;

  address internal constant DAI_V_TOKEN = 0x31b4D520F72f677D74d896432A837E1e828F0feF;

  address internal constant DAI_S_TOKEN = 0x95bE4B1ABD6fD238A561F4C3B1Bab4e32E7b425C;

  address internal constant DAI_ORACLE = 0x0d79df66BE487753B02D015Fb622DED7f0E9798d;

  address internal constant DAI_INTEREST_RATE_STRATEGY = 0xFc3f45e11f2CF20d2a2fe6Aa34e32B54D039487A;

  address internal constant USDC_UNDERLYING = 0x235eBFC0bE0E58cF267D1c5BCb8c03a002A711ed;

  address internal constant USDC_A_TOKEN = 0xCA34D8E65949BD67693F36C798C17A20eBDB76BF;

  address internal constant USDC_V_TOKEN = 0x18a1933c40e723f8fD300355E807dC5beC377B2B;

  address internal constant USDC_S_TOKEN = 0x7c8aA0dcaF8f7861dFA8fA1CEF6Dd86B3def1Fb9;

  address internal constant USDC_ORACLE = 0xAb5c49580294Aff77670F839ea425f5b78ab3Ae7;

  address internal constant USDC_INTEREST_RATE_STRATEGY =
    0x0382315971A5d7d75dB05686ac8bAC607CE1D0B8;

  address internal constant WETH_UNDERLYING = 0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6;

  address internal constant WETH_A_TOKEN = 0xCbf6e1215f0c99Ed3C3f6F0A5079283e5256db70;

  address internal constant WETH_V_TOKEN = 0x5Ae12D3d9ECDAEab9e176ff77BA15dBa1822A19D;

  address internal constant WETH_S_TOKEN = 0xC1d144f23A1492e1bDCa7cC65F59e24134A773Cc;

  address internal constant WETH_ORACLE = 0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e;

  address internal constant WETH_INTEREST_RATE_STRATEGY =
    0x66b179569bE9DfdDB0546cfC8f9d364C345794F7;

  address internal constant USDT_UNDERLYING = 0x3da37B4A2F5172580411DdcddDCcae857f9a7aE6;

  address internal constant USDT_A_TOKEN = 0x3DBF41D28fd2Eee83DC6a54f0Ec88bFaAbB34d89;

  address internal constant USDT_V_TOKEN = 0x4A52d3F52AB7d0d85FacF73Cb903e5Dd7fa7Db7C;

  address internal constant USDT_S_TOKEN = 0x35C8b58b02c0058cC1d29C8374aa86151Ac94949;

  address internal constant USDT_ORACLE = 0x0d79df66BE487753B02D015Fb622DED7f0E9798d;

  address internal constant USDT_INTEREST_RATE_STRATEGY =
    0x0382315971A5d7d75dB05686ac8bAC607CE1D0B8;

  address internal constant HOPE_UNDERLYING = 0x9bA97e0913Dd0fbd4E5fedA936db9D1f1C632273;

  address internal constant HOPE_A_TOKEN = 0x50F357357Ce6CA82924328aE2b534fc936C7A5B4;

  address internal constant HOPE_V_TOKEN = 0xf211432D15F1356F386f78ff26305012127368d0;

  address internal constant HOPE_S_TOKEN = 0xeaeC7e02Da80ac2A2EC2d3f159865167AB716F7a;

  address internal constant HOPE_ORACLE = 0x99f4E627093D6Bba806ea18284fB5C5EA1De6753;

  address internal constant HOPE_INTEREST_RATE_STRATEGY =
    0x66b179569bE9DfdDB0546cfC8f9d364C345794F7;

  address internal constant stHOPE_UNDERLYING = 0x89009881287EB51256141265B2f250b9960AaeE5;

  address internal constant stHOPE_A_TOKEN = 0xe034A5517C632A6B5C52D085d323a0fE96a8f913;

  address internal constant stHOPE_V_TOKEN = 0x1243d388C865Ca56E69765431e2ef1A299981AAB;

  address internal constant stHOPE_S_TOKEN = 0x7F5796BEF7743490BEa6D89fc21dA2A608E9D36e;

  address internal constant stHOPE_ORACLE = 0x99f4E627093D6Bba806ea18284fB5C5EA1De6753;

  address internal constant stHOPE_INTEREST_RATE_STRATEGY =
    0x66b179569bE9DfdDB0546cfC8f9d364C345794F7;
}
