export * as AaveGovernanceV2 from './AaveGovernanceV2';
export * as AaveSafetyModule from './AaveSafetyModule';
// autogenerated entrypoints
export * as AaveV3Sepolia from './AaveV3Sepolia';
export * as AaveV3Ethereum from './AaveV3Ethereum';
export * as AaveV3Goerli from './AaveV3Goerli';
