name: Draft release

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  draft-release:
    uses: bgd-labs/github-workflows/.github/workflows/draft-release.yml@69b7f9ab83d3a68d03d40dab09d1d20d0b29d243
