name: Head branch workflow

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    uses: bgd-labs/github-workflows/.github/workflows/foundry-test.yml@main
  release:
    if: github.event_name != 'pull_request'
    uses: bgd-labs/github-workflows/.github/workflows/release.yml@966d4148c278844679de00d30393cff78b79c7dc
